package com.tacmap.util

import org.junit.Assert.assertArrayEquals
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * Envelope crypto + the cross-platform wire fixtures.
 *
 * The fixtures are the load-bearing part. They were generated by a third
 * implementation (node's OpenSSL binding), not by this code and not by the
 * Swift code, so if Kotlin and Swift both open them then all three agree on
 * the wire format. Same trick SyncCryptoTest uses for the sync blob.
 */
class SealedEnvelopeTest {

    private val key = ByteArray(32) { it.toByte() } // 00 01 02 ... 1f
    private val label = "waypoints.json"

    private fun hex(s: String) = s.chunked(2).map { it.toInt(16).toByte() }.toByteArray()

    // MARK: round trips

    @Test fun sealFileOpenFileRoundTrips() {
        val plaintext = """[{"id":"wp-1","name":"OP North"}]""".toByteArray(Charsets.UTF_8)
        val blob = SealedEnvelope.sealFile(key, plaintext, label)
        assertTrue(SealedEnvelope.isSealedFile(blob))
        assertArrayEquals(plaintext, SealedEnvelope.openFile(key, blob, label))
    }

    @Test fun sealLineOpenLineRoundTrips() {
        val plaintext = """{"latitude":50.1}""".toByteArray(Charsets.UTF_8)
        val line = SealedEnvelope.sealLine(key, plaintext, TRACK_LABEL)
        assertTrue(SealedEnvelope.isSealedLine(line))
        assertArrayEquals(plaintext, SealedEnvelope.openLine(key, line, TRACK_LABEL))
    }

    @Test fun eachSealUsesAFreshIvSoCiphertextDiffers() {
        val pt = "same plaintext".toByteArray()
        val a = SealedEnvelope.sealFile(key, pt, label)
        val b = SealedEnvelope.sealFile(key, pt, label)
        assertFalse("random iv per seal", a.contentEquals(b))
        assertArrayEquals(pt, SealedEnvelope.openFile(key, a, label))
        assertArrayEquals(pt, SealedEnvelope.openFile(key, b, label))
    }

    // MARK: negative cases

    @Test fun wrongKeyFailsToOpen() {
        val blob = SealedEnvelope.sealFile(key, "secret".toByteArray(), label)
        assertNull(SealedEnvelope.openFile(ByteArray(32) { 0x7f }, blob, label))
    }

    @Test fun blobFromAnotherStoreFailsToOpen() {
        // The whole point of binding the label as AAD: someone drops
        // drawings.json's ciphertext in over waypoints.json and we reject it
        // rather than loading the wrong document.
        val blob = SealedEnvelope.sealFile(key, "payload".toByteArray(), "drawings.json")
        assertNull(SealedEnvelope.openFile(key, blob, "waypoints.json"))
    }

    @Test fun flippedBitFailsToOpen() {
        val blob = SealedEnvelope.sealFile(key, "payload".toByteArray(), label)
        blob[blob.size - 1] = (blob[blob.size - 1].toInt() xor 0x01).toByte()
        assertNull(SealedEnvelope.openFile(key, blob, label))
    }

    @Test fun plaintextIsNotMistakenForSealed() {
        assertFalse(SealedEnvelope.isSealedFile("""{"id":"wp-1"}""".toByteArray()))
        assertFalse(SealedEnvelope.isSealedLine("""{"latitude":50.1}"""))
        // and a short file can't false-positive the magic check
        assertFalse(SealedEnvelope.isSealedFile(byteArrayOf(0x54, 0x4D)))
    }

    @Test fun truncatedLineOpensToNullNotThrow() {
        val line = SealedEnvelope.sealLine(key, "x".toByteArray(), TRACK_LABEL)
        val torn = line.substring(0, line.length - 6) // interrupted append
        assertNull(SealedEnvelope.openLine(key, torn, TRACK_LABEL))
    }

    // MARK: cross-platform fixtures (see class doc)

    @Test fun opensFileFixtureFromOtherPlatforms() {
        val blob = hex(FILE_FIXTURE_HEX)
        assertTrue(SealedEnvelope.isSealedFile(blob))
        assertEquals(
            """[{"id":"wp-1","name":"OP North"}]""",
            SealedEnvelope.openFile(key, blob, "waypoints.json")!!.toString(Charsets.UTF_8)
        )
    }

    @Test fun opensLineFixtureFromOtherPlatforms() {
        assertEquals(
            """{"latitude":50.1,"longitude":-1.2,"elevationMetres":null,"timeEpochMs":1700000000000}""",
            SealedEnvelope.openLine(key, LINE_FIXTURE, TRACK_LABEL)!!.toString(Charsets.UTF_8)
        )
    }

    private companion object {
        const val TRACK_LABEL = "tracks/recording.ndjson"

        /** magic || iv || ct || tag, key = 00..1f, label = waypoints.json */
        const val FILE_FIXTURE_HEX =
            "544d5345414c010b0b0b0b0b0b0b0b0b0b0b0bf3f530c8eb4eb78bacb9368e8764f7f6ce9c6d30" +
                "7461b7459a508f1dfcc3f49a95f87d0d38c656a91e8bdc6c57a1c6c7cb"

        /** "v1:" || base64(iv || ct || tag), key = 00..1f, label = tracks/recording.ndjson */
        const val LINE_FIXTURE =
            "v1:DAwMDAwMDAwMDAwMj5F3mCpwHhqnkhJx47KqD4KF74DOAmhNRotlIDnqD8FbCwbjk6WzDHIPrvni" +
                "ibuvf1BNjs6ISZ1zHgKt7cZPpxEO1V+mI5RlaAhr4IGpqTaNReeEF1RadSyO/yDojjoswcAPDVQ="
    }
}
