// Generated by scripts/generate_localizations.py. Do not edit.
enum Messages {
    static func chatRecipientHeading() -> String {
        L10n.message("id.chat_recipient_heading", fallback: "RECIPIENT")
    }
    static func acknowledge() -> String {
        L10n.message("id.common_ok", fallback: "OK")
    }
    static func importFailed(_ detail: String) -> String {
        L10n.message("id.import_failed", fallback: "Import failed: %1$@", detail)
    }
    static func deviceLanguage() -> String {
        L10n.message("id.settings_language_device", fallback: "Device language")
    }
    static func languageSaveFailed() -> String {
        L10n.message("id.settings_language_save_failed", fallback: "Could not save the language setting. Try again.")
    }
    static func settingsLanguageTitle() -> String {
        L10n.message("id.settings_language_title", fallback: "Language")
    }
    static func dayCount(_ count: Int) -> String { L10n.quantity("day", count) }
    static func pointCount(_ count: Int) -> String { L10n.quantity("point", count) }
    static func drawingCount(_ count: Int) -> String { L10n.quantity("drawing", count) }
    static func waypointCount(_ count: Int) -> String { L10n.quantity("waypoint", count) }
    static func unitCount(_ count: Int) -> String { L10n.quantity("unit", count) }
    static func taskCount(_ count: Int) -> String { L10n.quantity("task", count) }
    static func markerCount(_ count: Int) -> String { L10n.quantity("marker", count) }
    static func lineCount(_ count: Int) -> String { L10n.quantity("line", count) }
    static func freeDrawCount(_ count: Int) -> String { L10n.quantity("free-draw", count) }
    static func areaCount(_ count: Int) -> String { L10n.quantity("area", count) }
    static func trackRecordedCount(_ count: Int) -> String { L10n.quantity("track_recorded", count) }
    static func trialRemainingCount(_ count: Int) -> String { L10n.quantity("trial_remaining", count) }
    static func unreadCount(_ count: Int) -> String { L10n.quantity("unread", count) }
    static func sendUnitsCount(_ count: Int) -> String { L10n.quantity("send_units", count) }
    static func minuteAgoCount(_ count: Int) -> String { L10n.quantity("minute_ago", count) }
    static func hourAgoCount(_ count: Int) -> String { L10n.quantity("hour_ago", count) }
    static func objectCount(_ count: Int) -> String { L10n.quantity("object", count) }
    static func layerCount(_ count: Int) -> String { L10n.quantity("layer", count) }
    static func newWaypointCount(_ count: Int) -> String { L10n.quantity("new_waypoint", count) }
    static func newDrawingCount(_ count: Int) -> String { L10n.quantity("new_drawing", count) }
    static func newLayerCount(_ count: Int) -> String { L10n.quantity("new_layer", count) }
}
