// Generated by scripts/generate_localizations.py. Do not edit.
enum SupportedLanguage: String, CaseIterable, Identifiable {
    case system
    case en = "en"
    case de = "de"
    var id: String { rawValue }
    var label: String {
        switch self {
        case .system: return Messages.deviceLanguage()
        case .en: return "English"
        case .de: return "Deutsch"
        }
    }
    static let resourceFolders: [String: String] = [
        "en": "en",
        "de": "de",
    ]
}
