import XCTest
@testable import TacticalMaps

/// Envelope crypto + the cross-platform wire fixtures.
///
/// The fixtures are the load-bearing part, and they are the same bytes the
/// Kotlin `SealedEnvelopeTest` checks. They were generated by a third
/// implementation (node's OpenSSL binding), not by this code and not by the
/// Kotlin code, so if Swift and Kotlin both open them then all three agree on
/// the wire format. Same trick SyncCryptoTests uses for the sync blob.
final class SealedEnvelopeTests: XCTestCase {

    private let key = Data((0..<32).map { UInt8($0) }) // 00 01 02 ... 1f
    private let label = "waypoints.json"
    private let trackLabel = "tracks/recording.ndjson"

    private func hex(_ s: String) -> Data {
        var out = Data()
        var i = s.startIndex
        while i < s.endIndex {
            let j = s.index(i, offsetBy: 2)
            out.append(UInt8(s[i..<j], radix: 16)!)
            i = j
        }
        return out
    }

    // MARK: round trips

    func testSealFileOpenFileRoundTrips() throws {
        let plaintext = Data(#"[{"id":"wp-1","name":"OP North"}]"#.utf8)
        let blob = try SealedEnvelope.sealFile(key: key, plaintext: plaintext, label: label)
        XCTAssertTrue(SealedEnvelope.isSealedFile(blob))
        XCTAssertEqual(SealedEnvelope.openFile(key: key, blob: blob, label: label), plaintext)
    }

    func testSealLineOpenLineRoundTrips() throws {
        let plaintext = Data(#"{"latitude":50.1}"#.utf8)
        let line = try SealedEnvelope.sealLine(key: key, plaintext: plaintext, label: trackLabel)
        XCTAssertTrue(SealedEnvelope.isSealedLine(line))
        XCTAssertEqual(SealedEnvelope.openLine(key: key, line: line, label: trackLabel), plaintext)
    }

    func testEachSealUsesAFreshIvSoCiphertextDiffers() throws {
        let pt = Data("same plaintext".utf8)
        let a = try SealedEnvelope.sealFile(key: key, plaintext: pt, label: label)
        let b = try SealedEnvelope.sealFile(key: key, plaintext: pt, label: label)
        XCTAssertNotEqual(a, b, "random iv per seal")
        XCTAssertEqual(SealedEnvelope.openFile(key: key, blob: a, label: label), pt)
        XCTAssertEqual(SealedEnvelope.openFile(key: key, blob: b, label: label), pt)
    }

    // MARK: negative cases

    func testWrongKeyFailsToOpen() throws {
        let blob = try SealedEnvelope.sealFile(key: key, plaintext: Data("secret".utf8), label: label)
        let wrong = Data(repeating: 0x7f, count: 32)
        XCTAssertNil(SealedEnvelope.openFile(key: wrong, blob: blob, label: label))
    }

    func testBlobFromAnotherStoreFailsToOpen() throws {
        // The whole point of binding the label as AAD: someone drops
        // drawings.json's ciphertext in over waypoints.json and we reject it
        // rather than loading the wrong document.
        let blob = try SealedEnvelope.sealFile(key: key, plaintext: Data("payload".utf8), label: "drawings.json")
        XCTAssertNil(SealedEnvelope.openFile(key: key, blob: blob, label: "waypoints.json"))
    }

    func testFlippedBitFailsToOpen() throws {
        var blob = try SealedEnvelope.sealFile(key: key, plaintext: Data("payload".utf8), label: label)
        blob[blob.count - 1] ^= 0x01
        XCTAssertNil(SealedEnvelope.openFile(key: key, blob: blob, label: label))
    }

    func testPlaintextIsNotMistakenForSealed() {
        XCTAssertFalse(SealedEnvelope.isSealedFile(Data(#"{"id":"wp-1"}"#.utf8)))
        XCTAssertFalse(SealedEnvelope.isSealedLine(#"{"latitude":50.1}"#))
        // and a short file can't false-positive the magic check
        XCTAssertFalse(SealedEnvelope.isSealedFile(Data([0x54, 0x4D])))
    }

    func testTruncatedLineOpensToNilNotCrash() throws {
        let line = try SealedEnvelope.sealLine(key: key, plaintext: Data("x".utf8), label: trackLabel)
        let torn = String(line.dropLast(6)) // interrupted append
        XCTAssertNil(SealedEnvelope.openLine(key: key, line: torn, label: trackLabel))
    }

    // MARK: cross-platform fixtures (see class doc)

    func testOpensFileFixtureFromOtherPlatforms() throws {
        let blob = hex(Self.fileFixtureHex)
        XCTAssertTrue(SealedEnvelope.isSealedFile(blob))
        let opened = try XCTUnwrap(SealedEnvelope.openFile(key: key, blob: blob, label: "waypoints.json"))
        XCTAssertEqual(String(decoding: opened, as: UTF8.self), #"[{"id":"wp-1","name":"OP North"}]"#)
    }

    func testOpensLineFixtureFromOtherPlatforms() throws {
        let opened = try XCTUnwrap(SealedEnvelope.openLine(key: key, line: Self.lineFixture, label: trackLabel))
        XCTAssertEqual(String(decoding: opened, as: UTF8.self),
                       #"{"latitude":50.1,"longitude":-1.2,"elevationMetres":null,"timeEpochMs":1700000000000}"#)
    }

    /// magic || iv || ct || tag, key = 00..1f, label = waypoints.json
    private static let fileFixtureHex =
        "544d5345414c010b0b0b0b0b0b0b0b0b0b0b0bf3f530c8eb4eb78bacb9368e8764f7f6ce9c6d30"
        + "7461b7459a508f1dfcc3f49a95f87d0d38c656a91e8bdc6c57a1c6c7cb"

    /// "v1:" || base64(iv || ct || tag), key = 00..1f, label = tracks/recording.ndjson
    private static let lineFixture =
        "v1:DAwMDAwMDAwMDAwMj5F3mCpwHhqnkhJx47KqD4KF74DOAmhNRotlIDnqD8FbCwbjk6WzDHIPrvni"
        + "ibuvf1BNjs6ISZ1zHgKt7cZPpxEO1V+mI5RlaAhr4IGpqTaNReeEF1RadSyO/yDojjoswcAPDVQ="
}
