/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: eb6ac108260bbc94a058e0fbd4b40015)
interface __BaseEnv_Env {
	CONN_LIMITER: RateLimit;
	ROOM_LIMITER: RateLimit;
	SYNC_ROOM: DurableObjectNamespace<import("./src/index").SyncRoom>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "SyncRoom";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
