#!/usr/bin/env python3
"""Generate native iOS/Android resources from the reviewed shared catalog.

Run with --check in CI to detect stale generated files. No network or packages.
Only UI strings belong here; never add serialized identifiers or protocol keys.
"""
from pathlib import Path
import argparse
import json
import plistlib
import re
import sys
from xml.sax.saxutils import escape

ROOT = Path(__file__).resolve().parents[1]
CATALOG = ROOT / 'localization/catalog.json'


def native(text, platform):
    return re.sub(r'\{(\d+)\}', lambda m: '%' + m[1] + ('$s' if platform == 'android' else '$@'), text)


def quoted(text, kotlin=False):
    result = json.dumps(text, ensure_ascii=False)
    return result.replace('$', '\\$') if kotlin else result


def android_value(text):
    # Quoting preserves leading/trailing spaces and repeated spaces in fragments.
    return '"' + escape(text.replace('\\', '\\\\').replace('"', '\\"').replace("'", "\\'").replace('\n', '\\n').replace('\t', '\\t')) + '"'


def outputs():
    catalog = json.loads(CATALOG.read_text())
    result = {}
    for language in ('en', 'de'):
        lines = ['/* Generated by scripts/generate_localizations.py. Edit localization/catalog.json. */']
        android = ['<?xml version="1.0" encoding="utf-8"?>', '<!-- Generated by scripts/generate_localizations.py. Edit localization/catalog.json. -->', '<resources>']
        for key, entry in sorted(catalog.items()):
            if 'ios' in entry['platforms']:
                lines.append(f'{quoted(native(entry["en"], "ios"))} = {quoted(native(entry[language], "ios"))};')
            if 'android' in entry['platforms']:
                android.append(f'    <string name="{key}">{android_value(native(entry[language], "android"))}</string>')
        android.append('</resources>')
        result[ROOT / f'ios/TacticalMaps/Resources/{language}.lproj/Localizable.strings'] = '\n'.join(lines) + '\n'
        values = 'values' if language == 'en' else 'values-de'
        result[ROOT / f'android/app/src/main/res/{values}/localized_strings.xml'] = '\n'.join(android) + '\n'
    index = ['// Generated by scripts/generate_localizations.py. Do not edit.',
             'package com.tacmap.localization', '', 'import com.tacmap.R', '',
             '/** Explicit resource references keep translations reachable during resource shrinking. */',
             'internal val localizedStringIds: Map<String, Int> = mapOf(']
    for key, entry in sorted(catalog.items()):
        if 'android' in entry['platforms']:
            index.append(f'    {quoted(native(entry["en"], "android"), True)} to R.string.{key},')
    index += [')', '']
    plurals = json.loads((ROOT / 'localization/plurals.json').read_text())
    for language in ('en', 'de'):
        stringsdict = {}
        xml = ['<?xml version="1.0" encoding="utf-8"?>', '<!-- Generated. Edit localization/plurals.json. -->', '<resources>']
        for noun, translations in plurals.items():
            one, other = translations[language]
            stringsdict['count.' + noun] = {
                'NSStringLocalizedFormatKey': '%#@count@',
                'count': {'NSStringFormatSpecTypeKey': 'NSStringPluralRuleType',
                          'NSStringFormatValueTypeKey': 'd', 'one': one, 'other': other}}
            xml += [f'    <plurals name="count_{noun.replace("-", "_")}">',
                    f'        <item quantity="one">{android_value(one)}</item>',
                    f'        <item quantity="other">{android_value(other)}</item>', '    </plurals>']
        xml += ['</resources>', '']
        result[ROOT / f'ios/TacticalMaps/Resources/{language}.lproj/Localizable.stringsdict'] = plistlib.dumps(stringsdict, sort_keys=False).decode()
        values = 'values' if language == 'en' else 'values-de'
        result[ROOT / f'android/app/src/main/res/{values}/localized_plurals.xml'] = '\n'.join(xml)
    index += ['internal val localizedPluralIds: Map<String, Int> = mapOf(']
    for noun in plurals:
        index.append(f'    {quoted(noun, True)} to R.plurals.count_{noun.replace("-", "_")},')
    index += [')', '', 'internal val englishPlurals: Map<String, Pair<String, String>> = mapOf(']
    for noun, translations in plurals.items():
        one, other = translations['en']
        index.append(f'    {quoted(noun, True)} to ({quoted(one, True)} to {quoted(other, True)}),')
    index += [')', '']
    result[ROOT / 'android/app/src/main/java/com/tacmap/localization/LocalizedStringIds.kt'] = '\n'.join(index)
    return result


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    stale = []
    for path, content in outputs().items():
        if args.check:
            if not path.exists() or path.read_text() != content:
                stale.append(str(path.relative_to(ROOT)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
    if stale:
        print('Stale localization resources: ' + ', '.join(stale), file=sys.stderr)
        return 1
    print('Localization resources are current.' if args.check else 'Generated iOS and Android localization resources.')
    return 0


if __name__ == '__main__':
    sys.exit(main())
