#!/usr/bin/env python3
"""Generate native resources and typed accessors from the shared locale manifest."""
from pathlib import Path
import argparse
import json
import plistlib
import re
import sys
from xml.sax.saxutils import escape
from localization_catalog import ROOT, CATEGORIES, load, validate


def native(text, platform):
    if re.search(r'\{\d+\}', text): text = text.replace('%', '%%')
    return re.sub(r'\{(\d+)\}', lambda m: '%' + m[1] + ('$s' if platform == 'android' else '$@'), text)


def quoted(text, kotlin=False):
    result = json.dumps(text, ensure_ascii=False)
    return result.replace('$', '\\$') if kotlin else result


def android_value(text):
    return '"' + escape(text.replace('\\', '\\\\').replace('"', '\\"').replace("'", "\\'").replace('\n', '\\n').replace('\t', '\\t')) + '"'


def outputs(root=ROOT, data=None):
    data = load(root) if data is None else data
    errors = validate(data)
    if errors: raise ValueError('\n'.join(errors))
    catalog, plurals = data['catalog'], data['plurals']
    locales = data['locales']['locales']
    system_accessor = catalog[data['locales']['systemChoiceMessage']]['accessor']
    result = {}
    banner = 'Generated by scripts/generate_localizations.py. Do not edit.'
    for locale in locales:
        tag = locale['tag']
        lines = ['/* ' + banner + ' */']
        android = ['<?xml version="1.0" encoding="utf-8"?>', '<!-- ' + banner + ' -->', '<resources>']
        for key, entry in sorted(catalog.items()):
            if 'ios' in entry['platforms']:
                lines.append(f'{quoted("id." + key)} = {quoted(native(entry[tag], "ios"))};')
                if entry.get('legacy', True):
                    lines.append(f'{quoted(native(entry["en"], "ios"))} = {quoted(native(entry[tag], "ios"))};')
            if 'android' in entry['platforms']:
                android.append(f'    <string name="{key}">{android_value(native(entry[tag], "android"))}</string>')
        android.append('</resources>')
        ios = root / 'ios/TacticalMaps/Resources' / (locale['iosFolder'] + '.lproj')
        values = root / 'android/app/src/main/res' / locale['androidFolder']
        result[ios / 'Localizable.strings'] = '\n'.join(lines) + '\n'
        result[values / 'localized_strings.xml'] = '\n'.join(android) + '\n'
        result[values / 'strings.xml'] = '<?xml version="1.0" encoding="utf-8"?>\n<!-- ' + banner + ' -->\n<resources>\n    <string name="app_name">TacMap</string>\n</resources>\n'
        result[ios / 'InfoPlist.strings'] = '/* ' + banner + ' */\n' + '\n'.join(
            f'{quoted(key)} = {quoted(entry[tag])};' for key, entry in sorted(data['permissions'].items())) + '\n'
        stringsdict, xml = {}, ['<?xml version="1.0" encoding="utf-8"?>', '<!-- ' + banner + ' -->', '<resources>']
        for noun, translations in plurals.items():
            forms = translations[tag]
            stringsdict['count.' + noun] = {
                'NSStringLocalizedFormatKey': '%#@count@',
                'count': {'NSStringFormatSpecTypeKey': 'NSStringPluralRuleType',
                          'NSStringFormatValueTypeKey': 'd', **{c: forms[c] for c in CATEGORIES if c in forms}}}
            xml.append(f'    <plurals name="count_{noun.replace(chr(45), chr(95))}">')
            xml += [f'        <item quantity="{c}">{android_value(forms[c])}</item>' for c in CATEGORIES if c in forms]
            xml.append('    </plurals>')
        xml.append('</resources>')
        result[ios / 'Localizable.stringsdict'] = plistlib.dumps(stringsdict, sort_keys=False).decode()
        result[values / 'localized_plurals.xml'] = '\n'.join(xml) + '\n'
    index = ['// ' + banner, 'package com.tacmap.localization', '', 'import com.tacmap.R', '',
             '/** Explicit references retain translations during resource shrinking. */',
             'internal val localizedStringIds: Map<String, Int> = mapOf(']
    for key, entry in sorted(catalog.items()):
        if 'android' in entry['platforms']:
            index.append(f'    {quoted("id." + key)} to R.string.{key},')
            if entry.get('legacy', True): index.append(f'    {quoted(native(entry["en"], "android"), True)} to R.string.{key},')
    index += [')', '', 'internal val localizedPluralIds: Map<String, Int> = mapOf(']
    index += [f'    {quoted(noun)} to R.plurals.count_{noun.replace(chr(45), chr(95))},' for noun in plurals]
    index += [')', '', 'internal val englishPlurals: Map<String, Pair<String, String>> = mapOf(']
    for noun, translations in plurals.items():
        forms = translations['en']
        index.append(f'    {quoted(noun)} to ({quoted(forms["one"], True)} to {quoted(forms["other"], True)}),')
    index += [')', '']
    result[root / 'android/app/src/main/java/com/tacmap/localization/LocalizedStringIds.kt'] = '\n'.join(index)
    # Typed migration surface. Unmigrated messages retain their legacy aliases.
    swift = ['// ' + banner, 'enum Messages {']
    kotlin = ['// ' + banner, 'package com.tacmap.localization', '', 'object Messages {']
    for key, entry in sorted(catalog.items()):
        if 'accessor' not in entry: continue
        name, parameters = entry['accessor'], entry.get('parameters', [])
        names = [p['name'] for p in parameters]
        if 'ios' in entry['platforms']:
            arguments = ', '.join('_ ' + n + ': String' for n in names)
            swift += [f'    static func {name}({arguments}) -> String {{',
                      f'        L10n.message({quoted("id." + key)}, fallback: {quoted(native(entry["en"], "ios"))}' + ''.join(', ' + n for n in names) + ')', '    }']
        if 'android' in entry['platforms']:
            arguments = ', '.join(n + ': String' for n in names)
            kotlin += [f'    fun {name}({arguments}): String =',
                       f'        L10n.message({quoted("id." + key)}, {quoted(native(entry["en"], "android"), True)}' + ''.join(', ' + n for n in names) + ')']
    for noun in plurals:
        accessor = ''.join(part.title() if i else part for i, part in enumerate(re.split('[-_]', noun))) + 'Count'
        if accessor in {e.get('accessor') for e in catalog.values()}: raise ValueError('Plural accessor collision: ' + accessor)
        swift += [f'    static func {accessor}(_ count: Int) -> String {{ L10n.quantity({quoted(noun)}, count) }}']
        kotlin += [f'    fun {accessor}(count: Int): String = L10n.quantity({quoted(noun)}, count)']
    result[root / 'ios/TacticalMaps/Util/Messages.swift'] = '\n'.join(swift + ['}', ''])
    result[root / 'android/app/src/main/java/com/tacmap/localization/Messages.kt'] = '\n'.join(kotlin + ['}', ''])
    swift = ['// ' + banner, 'enum SupportedLanguage: String, CaseIterable, Identifiable {', '    case system']
    swift += [f'    case {l["swiftCase"]} = {quoted(l["tag"])}' for l in locales]
    swift += ['    var id: String { rawValue }', '    var label: String {', '        switch self {', f'        case .system: return Messages.{system_accessor}()']
    swift += [f'        case .{l["swiftCase"]}: return {quoted(l["nativeName"])}' for l in locales]
    swift += ['        }', '    }', '    static let resourceFolders: [String: String] = [']
    swift += [f'        {quoted(l["tag"])}: {quoted(l["iosFolder"])},' for l in locales]
    swift += ['    ]', '}', '']
    result[root / 'ios/TacticalMaps/Util/SupportedLanguage.swift'] = '\n'.join(swift)
    kotlin = ['// ' + banner, 'package com.tacmap.localization', '',
              'enum class SupportedLanguage(val tag: String, private val nativeName: String) {', '    SYSTEM("system", ""),']
    kotlin += [f'    {l["kotlinCase"]}({quoted(l["tag"])}, {quoted(l["nativeName"], True)})' + (';' if i == len(locales)-1 else ',') for i, l in enumerate(locales)]
    kotlin += [f'    val label: String get() = if (this == SYSTEM) Messages.{system_accessor}() else nativeName', '}', '']
    result[root / 'android/app/src/main/java/com/tacmap/localization/SupportedLanguage.kt'] = '\n'.join(kotlin)
    result[root / 'android/app/src/main/res/xml/locales_config.xml'] = '<?xml version="1.0" encoding="utf-8"?>\n<!-- ' + banner + ' -->\n<locale-config xmlns:android="http://schemas.android.com/apk/res/android">\n' + ''.join(f'    <locale android:name="{l["tag"]}" />\n' for l in locales) + '</locale-config>\n'
    result[root / 'ios/Localizations.yml'] = '# ' + banner + '\noptions:\n  developmentLanguage: en\ntargets:\n  TacticalMaps:\n    info:\n      properties:\n        CFBundleLocalizations: ' + json.dumps([l['tag'] for l in locales]) + '\n'
    return result


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    try: generated = outputs()
    except ValueError as error:
        print(error, file=sys.stderr); return 1
    stale = []
    for path, content in generated.items():
        if args.check:
            if not path.exists() or path.read_text() != content: stale.append(str(path.relative_to(ROOT)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True); path.write_text(content)
    if stale:
        print('Stale localisation outputs: ' + ', '.join(stale), file=sys.stderr); return 1
    print('Localisation outputs are current.' if args.check else 'Generated native resources, language choices and typed messages.')
    return 0


if __name__ == '__main__':
    sys.exit(main())
