// Generated by scripts/generate_localizations.py. Do not edit.
package com.tacmap.localization

object Messages {
    fun chatRecipientHeading(): String =
        L10n.message("id.chat_recipient_heading", "RECIPIENT")
    fun acknowledge(): String =
        L10n.message("id.common_ok", "OK")
    fun importFailed(detail: String): String =
        L10n.message("id.import_failed", "Import failed: %1\$s", detail)
    fun decimalInputHint(): String =
        L10n.message("id.input_decimal_hint", "Use a decimal point or your language’s decimal separator. Do not use thousands separators.")
    fun deviceLanguage(): String =
        L10n.message("id.settings_language_device", "Device language")
    fun languageSaveFailed(): String =
        L10n.message("id.settings_language_save_failed", "Could not save the language setting. Try again.")
    fun settingsLanguageTitle(): String =
        L10n.message("id.settings_language_title", "Language")
    fun dayCount(count: Int): String = L10n.quantity("day", count)
    fun pointCount(count: Int): String = L10n.quantity("point", count)
    fun drawingCount(count: Int): String = L10n.quantity("drawing", count)
    fun waypointCount(count: Int): String = L10n.quantity("waypoint", count)
    fun unitCount(count: Int): String = L10n.quantity("unit", count)
    fun taskCount(count: Int): String = L10n.quantity("task", count)
    fun markerCount(count: Int): String = L10n.quantity("marker", count)
    fun lineCount(count: Int): String = L10n.quantity("line", count)
    fun freeDrawCount(count: Int): String = L10n.quantity("free-draw", count)
    fun areaCount(count: Int): String = L10n.quantity("area", count)
    fun trackRecordedCount(count: Int): String = L10n.quantity("track_recorded", count)
    fun trialRemainingCount(count: Int): String = L10n.quantity("trial_remaining", count)
    fun unreadCount(count: Int): String = L10n.quantity("unread", count)
    fun sendUnitsCount(count: Int): String = L10n.quantity("send_units", count)
    fun minuteAgoCount(count: Int): String = L10n.quantity("minute_ago", count)
    fun hourAgoCount(count: Int): String = L10n.quantity("hour_ago", count)
    fun objectCount(count: Int): String = L10n.quantity("object", count)
    fun layerCount(count: Int): String = L10n.quantity("layer", count)
    fun newWaypointCount(count: Int): String = L10n.quantity("new_waypoint", count)
    fun newDrawingCount(count: Int): String = L10n.quantity("new_drawing", count)
    fun newLayerCount(count: Int): String = L10n.quantity("new_layer", count)
}
