// Generated by scripts/generate_localizations.py. Do not edit.
package com.tacmap.localization

object Messages {
    fun appLockDataDamaged(): String =
        L10n.message("id.app_lock_data_damaged", "App Lock data is damaged and cannot be verified. Clear TacMap's app data in Android Settings to recover.")
    fun appLockDataDamagedMessage(): LocalizedMessage =
        LocalizedMessage("id.app_lock_data_damaged", "App Lock data is damaged and cannot be verified. Clear TacMap's app data in Android Settings to recover.", listOf())
    fun appLockUpdateFailed(): String =
        L10n.message("id.app_lock_update_failed", "App Lock storage could not be updated. The lock remains armed; enter your existing PIN.")
    fun appLockUpdateFailedMessage(): LocalizedMessage =
        LocalizedMessage("id.app_lock_update_failed", "App Lock storage could not be updated. The lock remains armed; enter your existing PIN.", listOf())
    fun backgroundSyncDisableFailed(): String =
        L10n.message("id.background_sync_disable_failed", "Background Unit Sync stopped, but its OFF setting could not be saved. Check available storage and turn it off again in Privacy & OPSEC.")
    fun backgroundSyncDisableFailedMessage(): LocalizedMessage =
        LocalizedMessage("id.background_sync_disable_failed", "Background Unit Sync stopped, but its OFF setting could not be saved. Check available storage and turn it off again in Privacy & OPSEC.", listOf())
    fun basemapRecoveryRequired(): String =
        L10n.message("id.basemap_recovery_required", "The saved basemap details could not be authenticated. A recovery copy and all imported maps were preserved. Tap Retry to reset the saved choice to the online map, or import/select a replacement map.")
    fun basemapRecoveryRequiredMessage(): LocalizedMessage =
        LocalizedMessage("id.basemap_recovery_required", "The saved basemap details could not be authenticated. A recovery copy and all imported maps were preserved. Tap Retry to reset the saved choice to the online map, or import/select a replacement map.", listOf())
    fun chatRecipientHeading(): String =
        L10n.message("id.chat_recipient_heading", "RECIPIENT")
    fun acknowledge(): String =
        L10n.message("id.common_ok", "OK")
    fun drawingsQuarantined(value: String): String =
        L10n.message("id.drawings_quarantined", "Saved drawings could not be read and were set aside (%1\$s). Starting with an empty map.", value)
    fun drawingsQuarantinedMessage(value: String): LocalizedMessage =
        LocalizedMessage("id.drawings_quarantined", "Saved drawings could not be read and were set aside (%1\$s). Starting with an empty map.", listOf(value))
    fun importFailed(detail: String): String =
        L10n.message("id.import_failed", "Import failed: %1\$s", detail)
    fun importFeatureSummary(waypoints: String, drawings: String, skipped: String): String =
        L10n.message("id.import_feature_summary", "Imported %1\$s waypoint(s) and %2\$s drawing(s)%3\$s", waypoints, drawings, skipped)
    fun importFeatureSummaryMessage(waypoints: String, drawings: String, skipped: String): LocalizedMessage =
        LocalizedMessage("id.import_feature_summary", "Imported %1\$s waypoint(s) and %2\$s drawing(s)%3\$s", listOf(waypoints, drawings, skipped))
    fun decimalInputHint(): String =
        L10n.message("id.input_decimal_hint", "Use a decimal point or your language’s decimal separator. Do not use thousands separators.")
    fun liveLocationApproximateGuidance(): String =
        L10n.message("id.live_location_approximate_guidance", "Approximate location cannot provide TacMap's on-device GPS position. Allow Precise location, then try again.")
    fun liveLocationApproximateGuidanceMessage(): LocalizedMessage =
        LocalizedMessage("id.live_location_approximate_guidance", "Approximate location cannot provide TacMap's on-device GPS position. Allow Precise location, then try again.", listOf())
    fun onlineBasemapsDisabled(): String =
        L10n.message("id.online_basemaps_disabled", "Online basemaps are off. Import an offline map pack, or enable online basemap tiles in Settings, Privacy & OPSEC.")
    fun onlineBasemapsDisabledMessage(): LocalizedMessage =
        LocalizedMessage("id.online_basemaps_disabled", "Online basemaps are off. Import an offline map pack, or enable online basemap tiles in Settings, Privacy & OPSEC.", listOf())
    fun pdfRotationUnsupported(value: String): String =
        L10n.message("id.pdf_rotation_unsupported", "This PDF's first page is rotated %1\$s°. TacMap cannot safely georeference rotated pages yet. Flatten the page rotation in a PDF editor or print it to a new PDF, then import that copy.", value)
    fun pdfRotationUnsupportedMessage(value: String): LocalizedMessage =
        LocalizedMessage("id.pdf_rotation_unsupported", "This PDF's first page is rotated %1\$s°. TacMap cannot safely georeference rotated pages yet. Flatten the page rotation in a PDF editor or print it to a new PDF, then import that copy.", listOf(value))
    fun privacySettingSaveFailed(): String =
        L10n.message("id.privacy_setting_save_failed", "Could not save this privacy setting. The previous setting remains active; check available storage and try again.")
    fun privacySettingSaveFailedMessage(): LocalizedMessage =
        LocalizedMessage("id.privacy_setting_save_failed", "Could not save this privacy setting. The previous setting remains active; check available storage and try again.", listOf())
    fun recordingActivationFailed(detail: String): String =
        L10n.message("id.recording_activation_failed", "Could not activate background track recording: %1\$s", detail)
    fun recordingActivationFailedMessage(detail: String): LocalizedMessage =
        LocalizedMessage("id.recording_activation_failed", "Could not activate background track recording: %1\$s", listOf(detail))
    fun recordingDiscardActive(value: String): String =
        L10n.message("id.recording_discard_active", "Recording will stop and the encrypted track log, including all %1\$s saved point(s), will be permanently deleted.", value)
    fun recordingDiscardActiveMessage(value: String): LocalizedMessage =
        LocalizedMessage("id.recording_discard_active", "Recording will stop and the encrypted track log, including all %1\$s saved point(s), will be permanently deleted.", listOf(value))
    fun recordingDiscardSaved(value: String): String =
        L10n.message("id.recording_discard_saved", "The encrypted track log and all %1\$s saved point(s) will be permanently deleted. Export GPX first if you need a copy.", value)
    fun recordingDiscardSavedMessage(value: String): LocalizedMessage =
        LocalizedMessage("id.recording_discard_saved", "The encrypted track log and all %1\$s saved point(s) will be permanently deleted. Export GPX first if you need a copy.", listOf(value))
    fun recordingNotificationHidden(): String =
        L10n.message("id.recording_notification_hidden", "Recording can continue, but Android may hide its ongoing notification from the notification drawer. You can still find TacMap in Active apps.")
    fun recordingNotificationHiddenMessage(): LocalizedMessage =
        LocalizedMessage("id.recording_notification_hidden", "Recording can continue, but Android may hide its ongoing notification from the notification drawer. You can still find TacMap in Active apps.", listOf())
    fun recordingPreciseRequiredRetry(): String =
        L10n.message("id.recording_precise_required_retry", "Approximate location cannot provide the precise GPS track TacMap records. Allow Precise location, then retry.")
    fun recordingPreciseRequiredRetryMessage(): LocalizedMessage =
        LocalizedMessage("id.recording_precise_required_retry", "Approximate location cannot provide the precise GPS track TacMap records. Allow Precise location, then retry.", listOf())
    fun relayRecoveryFailed(): String =
        L10n.message("id.relay_recovery_failed", "The saved Unit Sync relay was unsafe or obsolete. TacMap is using its secure default for this run, but could not repair the saved setting.")
    fun relayRecoveryFailedMessage(): LocalizedMessage =
        LocalizedMessage("id.relay_recovery_failed", "The saved Unit Sync relay was unsafe or obsolete. TacMap is using its secure default for this run, but could not repair the saved setting.", listOf())
    fun androidKeyProtectionHelp(): String =
        L10n.message("id.settings_android_key_protection_help", "Off: waypoints, drawings and tracks are encrypted with a key the device Keystore releases to this app automatically. Copied app files contain ciphertext, but code running as this app on a compromised device may ask the Keystore to decrypt.\n\nOn: Android Keystore requires a recent device credential or strong biometric before key use. Hardware backing varies by device and TacMap does not verify it, so a fully compromised system remains outside this protection. After the app is killed, nothing can read or write mission data until you unlock, including background track recording. Removing your device lockscreen can invalidate the key and make mission data unrecoverable.")
    fun headingHelp(): String =
        L10n.message("id.settings_heading_help", "North Up starts north-facing and keeps two-finger rotation available. Heading Up uses the phone compass to keep your pointing direction at the top of the map. It uses true north when a recent location is available. The compass marks bearings T for true north, or M when it falls back to magnetic north, and ? while waiting for a valid reading.")
    fun deviceLanguage(): String =
        L10n.message("id.settings_language_device", "Device language")
    fun languageSaveFailed(): String =
        L10n.message("id.settings_language_save_failed", "Could not save the language setting. Try again.")
    fun settingsLanguageTitle(): String =
        L10n.message("id.settings_language_title", "Language")
    fun onlineBasemapsHelp(): String =
        L10n.message("id.settings_online_basemaps_help", "Off by default. While off the map only draws imported offline maps, and no tile request leaves the device. While on, Esri or OpenTopoMap can see the ground you are looking at from your IP. Turn this off for a fully offline posture.")
    fun onlineLookupsHelp(): String =
        L10n.message("id.settings_online_lookups_help", "Off by default. When you turn this on, place-name search may use the device's geocoder. Elevation and weather send the map-centre coordinate (coarsened to ~110 m) to Open-Meteo. The terrain heat-map sends a 24 × 24 coordinate grid (coarsened to ~11 m) covering the visible map area. Turn this off when you need a fully offline/OPSEC posture.")
    fun syncCodeTooShort(value: String): String =
        L10n.message("id.sync_code_too_short", "Too short to be safe. Use at least %1\$s characters, or tap Generate.", value)
    fun syncCodeTooShortMessage(value: String): LocalizedMessage =
        LocalizedMessage("id.sync_code_too_short", "Too short to be safe. Use at least %1\$s characters, or tap Generate.", listOf(value))
    fun syncJoinLocationConsent(value: String): String =
        L10n.message("id.sync_join_location_consent", "To join, TacMap will enable Share my location and Background Unit Sync location. When Location access is allowed, your encrypted position will be sent while the app is open and approximately %1\$s while the screen is off.", value)
    fun syncJoinLocationConsentMessage(value: String): LocalizedMessage =
        LocalizedMessage("id.sync_join_location_consent", "To join, TacMap will enable Share my location and Background Unit Sync location. When Location access is allowed, your encrypted position will be sent while the app is open and approximately %1\$s while the screen is off.", listOf(value))
    fun syncLegacyMembershipHelp(): String =
        L10n.message("id.sync_legacy_membership_help", "Authenticated online membership is unavailable in legacy v2 rooms. Upgrade every device to a v3 room for relay-reported signed sessions.")
    fun syncLegacyMembershipHelpMessage(): LocalizedMessage =
        LocalizedMessage("id.sync_legacy_membership_help", "Authenticated online membership is unavailable in legacy v2 rooms. Upgrade every device to a v3 room for relay-reported signed sessions.", listOf())
    fun syncLivenessCaveat(): String =
        L10n.message("id.sync_liveness_caveat", "Identity and session signatures are verified, but connection liveness is relay-attested; it is not cryptographic proof that a peer is currently online and remains subject to the replay/rollback caveat above.")
    fun syncLivenessCaveatMessage(): LocalizedMessage =
        LocalizedMessage("id.sync_liveness_caveat", "Identity and session signatures are verified, but connection liveness is relay-attested; it is not cryptographic proof that a peer is currently online and remains subject to the replay/rollback caveat above.", listOf())
    fun syncMetadataMigrationFailed(): String =
        L10n.message("id.sync_metadata_migration_failed", "Saved Unit Sync metadata could not be migrated to private filenames. Check available storage, then unlock mission data and try again.")
    fun syncMetadataMigrationFailedMessage(): LocalizedMessage =
        LocalizedMessage("id.sync_metadata_migration_failed", "Saved Unit Sync metadata could not be migrated to private filenames. Check available storage, then unlock mission data and try again.", listOf())
    fun syncMetadataPrivacy(): String =
        L10n.message("id.sync_metadata_privacy", "Mission payload content is end-to-end encrypted. The relay still sees connection, routing, session, timing, size, and traffic metadata.")
    fun syncMetadataPrivacyMessage(): LocalizedMessage =
        LocalizedMessage("id.sync_metadata_privacy", "Mission payload content is end-to-end encrypted. The relay still sees connection, routing, session, timing, size, and traffic metadata.", listOf())
    fun trialExpiredDetails(value: String): String =
        L10n.message("id.trial_expired_details", "Your %1\$s-day free trial is over. Make a one-time purchase to keep using TacMap — live MGRS, GeoPDF maps, NATO APP-6 symbology and GeoJSON export.", value)
    fun trialExpiredDetailsMessage(value: String): LocalizedMessage =
        LocalizedMessage("id.trial_expired_details", "Your %1\$s-day free trial is over. Make a one-time purchase to keep using TacMap — live MGRS, GeoPDF maps, NATO APP-6 symbology and GeoJSON export.", listOf(value))
    fun trialRemainingDetails(value: String): String =
        L10n.message("id.trial_remaining_details", "You're on the free trial (%1\$s left). Unlock now for permanent access.", value)
    fun trialRemainingDetailsMessage(value: String): LocalizedMessage =
        LocalizedMessage("id.trial_remaining_details", "You're on the free trial (%1\$s left). Unlock now for permanent access.", listOf(value))
    fun billingReloadTheCurrentGooglePlayOfferBeforeTryingAgain(detail: String): String =
        L10n.message("id.ui_1_reload_the_current_google_play_offer_before_tr_0fcb92e6", "%1\$s Reload the current Google Play offer before trying again.", detail)
    fun billingReloadTheCurrentGooglePlayOfferBeforeTryingAgainMessage(detail: String): LocalizedMessage =
        LocalizedMessage("id.ui_1_reload_the_current_google_play_offer_before_tr_0fcb92e6", "%1\$s Reload the current Google Play offer before trying again.", listOf(detail))
    fun liveLocationPreciseNeeded(): String =
        L10n.message("id.ui_allow_precise_location_to_show_your_live_positio_0adb7f1b", "Allow Precise location to show your live position on the map.")
    fun liveLocationPreciseNeededMessage(): LocalizedMessage =
        LocalizedMessage("id.ui_allow_precise_location_to_show_your_live_positio_0adb7f1b", "Allow Precise location to show your live position on the map.", listOf())
    fun recordingPreciseRequiredShort(): String =
        L10n.message("id.ui_approximate_location_cannot_provide_the_precise__fa2a6228", "Approximate location cannot provide the precise GPS track TacMap records.")
    fun recordingPreciseRequiredShortMessage(): LocalizedMessage =
        LocalizedMessage("id.ui_approximate_location_cannot_provide_the_precise__fa2a6228", "Approximate location cannot provide the precise GPS track TacMap records.", listOf())
    fun liveLocationApproximateHint(): String =
        L10n.message("id.ui_approximate_location_is_on_open_settings_to_allo_49d6e949", "Approximate location is on. Open Settings to allow Precise location.")
    fun liveLocationApproximateHintMessage(): LocalizedMessage =
        LocalizedMessage("id.ui_approximate_location_is_on_open_settings_to_allo_49d6e949", "Approximate location is on. Open Settings to allow Precise location.", listOf())
    fun recordingActivationTimeout(): String =
        L10n.message("id.ui_background_recording_did_not_activate_in_time_tr_7f76c35b", "Background recording did not activate in time. Try starting it again.")
    fun recordingActivationTimeoutMessage(): LocalizedMessage =
        LocalizedMessage("id.ui_background_recording_did_not_activate_in_time_tr_7f76c35b", "Background recording did not activate in time. Try starting it again.", listOf())
    fun recordingServiceStopped(): String =
        L10n.message("id.ui_background_recording_stopped_unexpectedly_your_s_4fb5f807", "Background recording stopped unexpectedly. Your saved track was preserved.")
    fun recordingServiceStoppedMessage(): LocalizedMessage =
        LocalizedMessage("id.ui_background_recording_stopped_unexpectedly_your_s_4fb5f807", "Background recording stopped unexpectedly. Your saved track was preserved.", listOf())
    fun liveLocationCentre(): String =
        L10n.message("id.ui_centre_on_my_location_82529ff7", "Centre on My Location")
    fun liveLocationCentreMessage(): LocalizedMessage =
        LocalizedMessage("id.ui_centre_on_my_location_82529ff7", "Centre on My Location", listOf())
    fun liveLocationCentrePreciseHint(): String =
        L10n.message("id.ui_centres_the_map_on_your_latest_precise_location_a4532c96", "Centres the map on your latest precise location.")
    fun liveLocationCentrePreciseHintMessage(): LocalizedMessage =
        LocalizedMessage("id.ui_centres_the_map_on_your_latest_precise_location_a4532c96", "Centres the map on your latest precise location.", listOf())
    fun billingCheckingGooglePlayForYourPurchase(): String =
        L10n.message("id.ui_checking_google_play_for_your_purchase_fa0f4b1f", "Checking Google Play for your purchase…")
    fun billingCheckingGooglePlayForYourPurchaseMessage(): LocalizedMessage =
        LocalizedMessage("id.ui_checking_google_play_for_your_purchase_fa0f4b1f", "Checking Google Play for your purchase…", listOf())
    fun billingConnectingToGooglePlay(): String =
        L10n.message("id.ui_connecting_to_google_play_75d0cdf5", "Connecting to Google Play…")
    fun billingConnectingToGooglePlayMessage(): LocalizedMessage =
        LocalizedMessage("id.ui_connecting_to_google_play_75d0cdf5", "Connecting to Google Play…", listOf())
    fun trackDiscardFailed(detail: String): String =
        L10n.message("id.ui_could_not_discard_the_saved_track_1_01f1dcdf", "Could not discard the saved track: %1\$s", detail)
    fun trackDiscardFailedMessage(detail: String): LocalizedMessage =
        LocalizedMessage("id.ui_could_not_discard_the_saved_track_1_01f1dcdf", "Could not discard the saved track: %1\$s", listOf(detail))
    fun trackReencryptFailed(detail: String): String =
        L10n.message("id.ui_could_not_encrypt_the_recovered_track_1_1986bd1a", "Could not encrypt the recovered track: %1\$s", detail)
    fun trackReencryptFailedMessage(detail: String): LocalizedMessage =
        LocalizedMessage("id.ui_could_not_encrypt_the_recovered_track_1_1986bd1a", "Could not encrypt the recovered track: %1\$s", listOf(detail))
    fun trackReadFailed(detail: String): String =
        L10n.message("id.ui_could_not_read_the_saved_track_1_fd3205b4", "Could not read the saved track: %1\$s", detail)
    fun trackReadFailedMessage(detail: String): LocalizedMessage =
        LocalizedMessage("id.ui_could_not_read_the_saved_track_1_fd3205b4", "Could not read the saved track: %1\$s", listOf(detail))
    fun couldNotSaveDrawingsToDisk(detail1: String): String =
        L10n.message("id.ui_could_not_save_drawings_to_disk_1_165e4ac6", "Could not save drawings to disk: %1\$s", detail1)
    fun couldNotSaveDrawingsToDiskMessage(detail1: String): LocalizedMessage =
        LocalizedMessage("id.ui_could_not_save_drawings_to_disk_1_165e4ac6", "Could not save drawings to disk: %1\$s", listOf(detail1))
    fun couldNotSaveDrawingsToDiskTheChangeWasReverted(detail1: String): String =
        L10n.message("id.ui_could_not_save_drawings_to_disk_the_change_was_r_ac83ca6c", "Could not save drawings to disk; the change was reverted: %1\$s", detail1)
    fun couldNotSaveDrawingsToDiskTheChangeWasRevertedMessage(detail1: String): LocalizedMessage =
        LocalizedMessage("id.ui_could_not_save_drawings_to_disk_the_change_was_r_ac83ca6c", "Could not save drawings to disk; the change was reverted: %1\$s", listOf(detail1))
    fun couldNotSaveWaypointsToDiskTheChangeWasReverted(detail1: String): String =
        L10n.message("id.ui_could_not_save_waypoints_to_disk_the_change_was__97475445", "Could not save waypoints to disk; the change was reverted: %1\$s", detail1)
    fun couldNotSaveWaypointsToDiskTheChangeWasRevertedMessage(detail1: String): LocalizedMessage =
        LocalizedMessage("id.ui_could_not_save_waypoints_to_disk_the_change_was__97475445", "Could not save waypoints to disk; the change was reverted: %1\$s", listOf(detail1))
    fun recordingBackgroundStartFailed(detail: String): String =
        L10n.message("id.ui_could_not_start_background_recording_1_cdb42e3d", "Could not start background recording: %1\$s", detail)
    fun recordingBackgroundStartFailedMessage(detail: String): LocalizedMessage =
        LocalizedMessage("id.ui_could_not_start_background_recording_1_cdb42e3d", "Could not start background recording: %1\$s", listOf(detail))
    fun recordingStartFailed(detail: String): String =
        L10n.message("id.ui_could_not_start_recording_safely_1_e3b8a79c", "Could not start recording safely: %1\$s", detail)
    fun recordingStartFailedMessage(detail: String): LocalizedMessage =
        LocalizedMessage("id.ui_could_not_start_recording_safely_1_e3b8a79c", "Could not start recording safely: %1\$s", listOf(detail))
    fun recordingVerifyFailed(): String =
        L10n.message("id.ui_could_not_verify_the_saved_track_before_recordin_74d65e13", "Could not verify the saved track before recording.")
    fun recordingVerifyFailedMessage(): LocalizedMessage =
        LocalizedMessage("id.ui_could_not_verify_the_saved_track_before_recordin_74d65e13", "Could not verify the saved track before recording.", listOf())
    fun drawingsAreEncryptedAndLocked(detail1: String): String =
        L10n.message("id.ui_drawings_are_encrypted_and_locked_1_45b3c976", "Drawings are encrypted and locked. %1\$s", detail1)
    fun drawingsAreEncryptedAndLockedMessage(detail1: String): LocalizedMessage =
        LocalizedMessage("id.ui_drawings_are_encrypted_and_locked_1_45b3c976", "Drawings are encrypted and locked. %1\$s", listOf(detail1))
    fun drawingsAreLockedAndTheChangeWasNotSaved(): String =
        L10n.message("id.ui_drawings_are_locked_and_the_change_was_not_saved_2b37305f", "Drawings are locked and the change was not saved.")
    fun drawingsAreLockedAndTheChangeWasNotSavedMessage(): LocalizedMessage =
        LocalizedMessage("id.ui_drawings_are_locked_and_the_change_was_not_saved_2b37305f", "Drawings are locked and the change was not saved.", listOf())
    fun liveLocationEnable(): String =
        L10n.message("id.ui_enable_live_location_ce184825", "Enable Live Location")
    fun liveLocationEnableMessage(): LocalizedMessage =
        LocalizedMessage("id.ui_enable_live_location_ce184825", "Enable Live Location", listOf())
    fun liveLocationEnablePrecise(): String =
        L10n.message("id.ui_enable_precise_location_177e9850", "Enable Precise Location")
    fun liveLocationEnablePreciseMessage(): LocalizedMessage =
        LocalizedMessage("id.ui_enable_precise_location_177e9850", "Enable Precise Location", listOf())
    fun recordingExistingTrack(): String =
        L10n.message("id.ui_export_or_discard_the_saved_track_before_startin_11ec4f4c", "Export or discard the saved track before starting a new recording.")
    fun recordingExistingTrackMessage(): LocalizedMessage =
        LocalizedMessage("id.ui_export_or_discard_the_saved_track_before_startin_11ec4f4c", "Export or discard the saved track before starting a new recording.", listOf())
    fun billingGooglePlayBillingIsUnavailableCheckThePlayStorec6d54b3b(): String =
        L10n.message("id.ui_google_play_billing_is_unavailable_check_the_pla_c6d54b3b", "Google Play Billing is unavailable. Check the Play Store app and account, then try again.")
    fun billingGooglePlayBillingIsUnavailableCheckThePlayStorec6d54b3bMessage(): LocalizedMessage =
        LocalizedMessage("id.ui_google_play_billing_is_unavailable_check_the_pla_c6d54b3b", "Google Play Billing is unavailable. Check the Play Store app and account, then try again.", listOf())
    fun billingGooglePlayBillingIsUnavailableCheckThePlayStore(): String =
        L10n.message("id.ui_google_play_billing_is_unavailable_check_the_pla_f06ceae3", "Google Play Billing is unavailable. Check the Play Store app and account, then retry.")
    fun billingGooglePlayBillingIsUnavailableCheckThePlayStoreMessage(): LocalizedMessage =
        LocalizedMessage("id.ui_google_play_billing_is_unavailable_check_the_pla_f06ceae3", "Google Play Billing is unavailable. Check the Play Store app and account, then retry.", listOf())
    fun billingGooglePlayBillingIsUnavailableOnThisDeviceOr(): String =
        L10n.message("id.ui_google_play_billing_is_unavailable_on_this_devic_bf7caddb", "Google Play Billing is unavailable on this device or account. Check Play Store setup, then retry.")
    fun billingGooglePlayBillingIsUnavailableOnThisDeviceOrMessage(): LocalizedMessage =
        LocalizedMessage("id.ui_google_play_billing_is_unavailable_on_this_devic_bf7caddb", "Google Play Billing is unavailable on this device or account. Check Play Store setup, then retry.", listOf())
    fun billingGooglePlayConnectionTimedOut(): String =
        L10n.message("id.ui_google_play_connection_timed_out_11fc9cf9", "Google Play connection timed out.")
    fun billingGooglePlayConnectionTimedOutMessage(): LocalizedMessage =
        LocalizedMessage("id.ui_google_play_connection_timed_out_11fc9cf9", "Google Play connection timed out.", listOf())
    fun billingGooglePlayCouldNotCheckYourPurchaseYourKnown(): String =
        L10n.message("id.ui_google_play_could_not_check_your_purchase_your_k_bdc2b5f8", "Google Play could not check your purchase. Your known-good access has not been changed. Retry when Play is available.")
    fun billingGooglePlayCouldNotCheckYourPurchaseYourKnownMessage(): LocalizedMessage =
        LocalizedMessage("id.ui_google_play_could_not_check_your_purchase_your_k_bdc2b5f8", "Google Play could not check your purchase. Your known-good access has not been changed. Retry when Play is available.", listOf())
    fun billingGooglePlayCouldNotConfirmThePurchaseRetryTo(): String =
        L10n.message("id.ui_google_play_could_not_confirm_the_purchase_retry_b5f9a1e0", "Google Play could not confirm the purchase. Retry to check your ownership before purchasing again.")
    fun billingGooglePlayCouldNotConfirmThePurchaseRetryToMessage(): LocalizedMessage =
        LocalizedMessage("id.ui_google_play_could_not_confirm_the_purchase_retry_b5f9a1e0", "Google Play could not confirm the purchase. Retry to check your ownership before purchasing again.", listOf())
    fun billingGooglePlayCouldNotReturnTheTacmapUnlockProduct(): String =
        L10n.message("id.ui_google_play_could_not_return_the_tacmap_unlock_p_894c2cad", "Google Play could not return the TacMap unlock product. Check your connection and retry.")
    fun billingGooglePlayCouldNotReturnTheTacmapUnlockProductMessage(): LocalizedMessage =
        LocalizedMessage("id.ui_google_play_could_not_return_the_tacmap_unlock_p_894c2cad", "Google Play could not return the TacMap unlock product. Check your connection and retry.", listOf())
    fun billingGooglePlayCouldNotStartThePurchaseCheckYour(): String =
        L10n.message("id.ui_google_play_could_not_start_the_purchase_check_y_a7caaf1c", "Google Play could not start the purchase. Check your connection and try again.")
    fun billingGooglePlayCouldNotStartThePurchaseCheckYourMessage(): LocalizedMessage =
        LocalizedMessage("id.ui_google_play_could_not_start_the_purchase_check_y_a7caaf1c", "Google Play could not start the purchase. Check your connection and try again.", listOf())
    fun billingGooglePlayDidNotReturnATacmapPurchaseRetry(): String =
        L10n.message("id.ui_google_play_did_not_return_a_tacmap_purchase_ret_457626f6", "Google Play did not return a TacMap purchase. Retry to check your ownership before purchasing again.")
    fun billingGooglePlayDidNotReturnATacmapPurchaseRetryMessage(): LocalizedMessage =
        LocalizedMessage("id.ui_google_play_did_not_return_a_tacmap_purchase_ret_457626f6", "Google Play did not return a TacMap purchase. Retry to check your ownership before purchasing again.", listOf())
    fun billingGooglePlayDisconnectedBeforeTheOperationCompleted(): String =
        L10n.message("id.ui_google_play_disconnected_before_the_operation_co_a70c8754", "Google Play disconnected before the operation completed.")
    fun billingGooglePlayDisconnectedBeforeTheOperationCompletedMessage(): LocalizedMessage =
        LocalizedMessage("id.ui_google_play_disconnected_before_the_operation_co_a70c8754", "Google Play disconnected before the operation completed.", listOf())
    fun billingGooglePlayHasNotCompletedThisPurchaseRetryTo(): String =
        L10n.message("id.ui_google_play_has_not_completed_this_purchase_retr_9b191482", "Google Play has not completed this purchase. Retry to check its status.")
    fun billingGooglePlayHasNotCompletedThisPurchaseRetryToMessage(): LocalizedMessage =
        LocalizedMessage("id.ui_google_play_has_not_completed_this_purchase_retr_9b191482", "Google Play has not completed this purchase. Retry to check its status.", listOf())
    fun billingGooglePlayNeedsAttention(): String =
        L10n.message("id.ui_google_play_needs_attention_b73fea15", "Google Play needs attention")
    fun billingGooglePlayNeedsAttentionMessage(): LocalizedMessage =
        LocalizedMessage("id.ui_google_play_needs_attention_b73fea15", "Google Play needs attention", listOf())
    fun billingGooglePlayOwnershipCheckTimedOut(): String =
        L10n.message("id.ui_google_play_ownership_check_timed_out_942987fb", "Google Play ownership check timed out.")
    fun billingGooglePlayOwnershipCheckTimedOutMessage(): LocalizedMessage =
        LocalizedMessage("id.ui_google_play_ownership_check_timed_out_942987fb", "Google Play ownership check timed out.", listOf())
    fun billingGooglePlayPurchaseAcknowledgementTimedOut(): String =
        L10n.message("id.ui_google_play_purchase_acknowledgement_timed_out_08292ff0", "Google Play purchase acknowledgement timed out.")
    fun billingGooglePlayPurchaseAcknowledgementTimedOutMessage(): LocalizedMessage =
        LocalizedMessage("id.ui_google_play_purchase_acknowledgement_timed_out_08292ff0", "Google Play purchase acknowledgement timed out.", listOf())
    fun billingGooglePlayTookTooLongToLoadTheCurrent(): String =
        L10n.message("id.ui_google_play_took_too_long_to_load_the_current_pr_a63fad1d", "Google Play took too long to load the current price. Retry Google Play.")
    fun billingGooglePlayTookTooLongToLoadTheCurrentMessage(): LocalizedMessage =
        LocalizedMessage("id.ui_google_play_took_too_long_to_load_the_current_pr_a63fad1d", "Google Play took too long to load the current price. Retry Google Play.", listOf())
    fun recordingGpsOff(): String =
        L10n.message("id.ui_gps_is_turned_off_recording_stopped_ee16972d", "GPS is turned off; recording stopped.")
    fun recordingGpsOffMessage(): LocalizedMessage =
        LocalizedMessage("id.ui_gps_is_turned_off_recording_stopped_ee16972d", "GPS is turned off; recording stopped.", listOf())
    fun recordingGpsRequired(): String =
        L10n.message("id.ui_gps_is_turned_off_turn_on_device_location_servic_645dc271", "GPS is turned off. Turn on device location services, then retry.")
    fun recordingGpsRequiredMessage(): LocalizedMessage =
        LocalizedMessage("id.ui_gps_is_turned_off_turn_on_device_location_servic_645dc271", "GPS is turned off. Turn on device location services, then retry.", listOf())
    fun recordingGpsDisabled(): String =
        L10n.message("id.ui_gps_was_turned_off_recording_stopped_d4078430", "GPS was turned off; recording stopped.")
    fun recordingGpsDisabledMessage(): LocalizedMessage =
        LocalizedMessage("id.ui_gps_was_turned_off_recording_stopped_d4078430", "GPS was turned off; recording stopped.", listOf())
    fun billingLoadingPriceFromGooglePlay(): String =
        L10n.message("id.ui_loading_price_from_google_play_ce945d9e", "Loading price from Google Play…")
    fun billingLoadingPriceFromGooglePlayMessage(): LocalizedMessage =
        LocalizedMessage("id.ui_loading_price_from_google_play_ce945d9e", "Loading price from Google Play…", listOf())
    fun recordingAccessUnavailable(): String =
        L10n.message("id.ui_location_access_became_unavailable_recording_sto_3c08130f", "Location access became unavailable; recording stopped.")
    fun recordingAccessUnavailableMessage(): LocalizedMessage =
        LocalizedMessage("id.ui_location_access_became_unavailable_recording_sto_3c08130f", "Location access became unavailable; recording stopped.", listOf())
    fun liveLocationDisabledHint(): String =
        L10n.message("id.ui_location_access_is_off_opens_settings_so_you_can_aa125240", "Location access is off. Opens Settings so you can enable it.")
    fun liveLocationDisabledHintMessage(): LocalizedMessage =
        LocalizedMessage("id.ui_location_access_is_off_opens_settings_so_you_can_aa125240", "Location access is off. Opens Settings so you can enable it.", listOf())
    fun liveLocationRestrictedAndroidHint(): String =
        L10n.message("id.ui_location_access_is_restricted_by_this_device_rev_50e0726b", "Location access is restricted by this device. Review Location settings.")
    fun liveLocationRestrictedAndroidHintMessage(): LocalizedMessage =
        LocalizedMessage("id.ui_location_access_is_restricted_by_this_device_rev_50e0726b", "Location access is restricted by this device. Review Location settings.", listOf())
    fun recordingPermissionLost(): String =
        L10n.message("id.ui_location_permission_was_removed_recording_stoppe_4d281d01", "Location permission was removed; recording stopped.")
    fun recordingPermissionLostMessage(): LocalizedMessage =
        LocalizedMessage("id.ui_location_permission_was_removed_recording_stoppe_4d281d01", "Location permission was removed; recording stopped.", listOf())
    fun liveLocationRestricted(): String =
        L10n.message("id.ui_location_restricted_7b8c5d17", "Location Restricted")
    fun liveLocationRestrictedMessage(): LocalizedMessage =
        LocalizedMessage("id.ui_location_restricted_7b8c5d17", "Location Restricted", listOf())
    fun billingNoActivePurchaseWasFoundRetryToLoadThe(): String =
        L10n.message("id.ui_no_active_purchase_was_found_retry_to_load_the_u_fe8d025d", "No active purchase was found. Retry to load the unlock product.")
    fun billingNoActivePurchaseWasFoundRetryToLoadTheMessage(): LocalizedMessage =
        LocalizedMessage("id.ui_no_active_purchase_was_found_retry_to_load_the_u_fe8d025d", "No active purchase was found. Retry to load the unlock product.", listOf())
    fun billingNoActiveTacmapPurchaseWasFoundOnThisGoogle(): String =
        L10n.message("id.ui_no_active_tacmap_purchase_was_found_on_this_goog_f745c3e8", "No active TacMap purchase was found on this Google Play account.")
    fun billingNoActiveTacmapPurchaseWasFoundOnThisGoogleMessage(): LocalizedMessage =
        LocalizedMessage("id.ui_no_active_tacmap_purchase_was_found_on_this_goog_f745c3e8", "No active TacMap purchase was found on this Google Play account.", listOf())
    fun billingNotNow(): String =
        L10n.message("id.ui_not_now_a0e63d7c", "Not now")
    fun billingNotNowMessage(): LocalizedMessage =
        LocalizedMessage("id.ui_not_now_a0e63d7c", "Not now", listOf())
    fun liveLocationSettings(): String =
        L10n.message("id.ui_open_location_settings_4295919a", "Open Location Settings")
    fun liveLocationSettingsMessage(): LocalizedMessage =
        LocalizedMessage("id.ui_open_location_settings_4295919a", "Open Location Settings", listOf())
    fun billingOpeningGooglePlay(): String =
        L10n.message("id.ui_opening_google_play_3d38b231", "Opening Google Play…")
    fun billingOpeningGooglePlayMessage(): LocalizedMessage =
        LocalizedMessage("id.ui_opening_google_play_3d38b231", "Opening Google Play…", listOf())
    fun recordingPreciseRequired(): String =
        L10n.message("id.ui_precise_location_permission_is_required_to_recor_4e3a2e91", "Precise location permission is required to record a GPS track.")
    fun recordingPreciseRequiredMessage(): LocalizedMessage =
        LocalizedMessage("id.ui_precise_location_permission_is_required_to_recor_4e3a2e91", "Precise location permission is required to record a GPS track.", listOf())
    fun recordingPrecisionLost(): String =
        L10n.message("id.ui_precise_location_was_removed_recording_stopped_a_00f6cc68", "Precise location was removed; recording stopped. Approximate location is not accurate enough for a GPS track.")
    fun recordingPrecisionLostMessage(): LocalizedMessage =
        LocalizedMessage("id.ui_precise_location_was_removed_recording_stopped_a_00f6cc68", "Precise location was removed; recording stopped. Approximate location is not accurate enough for a GPS track.", listOf())
    fun billingPurchaseCancelledYouHaveNotBeenCharged(): String =
        L10n.message("id.ui_purchase_cancelled_you_have_not_been_charged_4962904b", "Purchase cancelled. You have not been charged.")
    fun billingPurchaseCancelledYouHaveNotBeenChargedMessage(): LocalizedMessage =
        LocalizedMessage("id.ui_purchase_cancelled_you_have_not_been_charged_4962904b", "Purchase cancelled. You have not been charged.", listOf())
    fun recordingSessionKeyUnavailable(): String =
        L10n.message("id.ui_recording_stopped_because_its_session_key_was_un_6082de71", "Recording stopped because its session key was unavailable.")
    fun recordingSessionKeyUnavailableMessage(): LocalizedMessage =
        LocalizedMessage("id.ui_recording_stopped_because_its_session_key_was_un_6082de71", "Recording stopped because its session key was unavailable.", listOf())
    fun recoveryCopyFallback(): String =
        L10n.message("id.ui_recovery_copy_6f7749ab", "recovery copy")
    fun billingRetryGooglePlay(): String =
        L10n.message("id.ui_retry_google_play_8520938e", "Retry Google Play")
    fun billingRetryGooglePlayMessage(): LocalizedMessage =
        LocalizedMessage("id.ui_retry_google_play_8520938e", "Retry Google Play", listOf())
    fun trackStopBeforeDiscard(): String =
        L10n.message("id.ui_stop_recording_before_discarding_the_saved_track_fba88fe8", "Stop recording before discarding the saved track.")
    fun trackStopBeforeDiscardMessage(): LocalizedMessage =
        LocalizedMessage("id.ui_stop_recording_before_discarding_the_saved_track_fba88fe8", "Stop recording before discarding the saved track.", listOf())
    fun billingTacmapCheckedGooglePlayButCouldnTSaveThe(): String =
        L10n.message("id.ui_tacmap_checked_google_play_but_couldn_t_save_the_2f769b9c", "TacMap checked Google Play but couldn't save the latest unlock status securely. Your existing access was kept. Free some device storage, then retry.")
    fun billingTacmapCheckedGooglePlayButCouldnTSaveTheMessage(): LocalizedMessage =
        LocalizedMessage("id.ui_tacmap_checked_google_play_but_couldn_t_save_the_2f769b9c", "TacMap checked Google Play but couldn't save the latest unlock status securely. Your existing access was kept. Free some device storage, then retry.", listOf())
    fun billingTacmapCouldNotConnectToGooglePlayCheckYour(): String =
        L10n.message("id.ui_tacmap_could_not_connect_to_google_play_check_yo_51a569fd", "TacMap could not connect to Google Play. Check your connection and retry.")
    fun billingTacmapCouldNotConnectToGooglePlayCheckYourMessage(): LocalizedMessage =
        LocalizedMessage("id.ui_tacmap_could_not_connect_to_google_play_check_yo_51a569fd", "TacMap could not connect to Google Play. Check your connection and retry.", listOf())
    fun billingTacmapCouldNotLoadTheGooglePlayPriceCheck(): String =
        L10n.message("id.ui_tacmap_could_not_load_the_google_play_price_chec_8f65f352", "TacMap could not load the Google Play price. Check your connection and retry.")
    fun billingTacmapCouldNotLoadTheGooglePlayPriceCheckMessage(): LocalizedMessage =
        LocalizedMessage("id.ui_tacmap_could_not_load_the_google_play_price_chec_8f65f352", "TacMap could not load the Google Play price. Check your connection and retry.", listOf())
    fun billingTacmapCouldNotSafelySaveThePurchaseDoNot(): String =
        L10n.message("id.ui_tacmap_could_not_safely_save_the_purchase_do_not_9d49f678", "TacMap could not safely save the purchase. Do not purchase again; free some device storage, then retry Restore purchase.")
    fun billingTacmapCouldNotSafelySaveThePurchaseDoNotMessage(): LocalizedMessage =
        LocalizedMessage("id.ui_tacmap_could_not_safely_save_the_purchase_do_not_9d49f678", "TacMap could not safely save the purchase. Do not purchase again; free some device storage, then retry Restore purchase.", listOf())
    fun billingTacmapCouldNotSafelySaveTheRestoredEntitlementFree(): String =
        L10n.message("id.ui_tacmap_could_not_safely_save_the_restored_entitl_87d67d86", "TacMap could not safely save the restored entitlement. Free some device storage and retry.")
    fun billingTacmapCouldNotSafelySaveTheRestoredEntitlementFreeMessage(): LocalizedMessage =
        LocalizedMessage("id.ui_tacmap_could_not_safely_save_the_restored_entitl_87d67d86", "TacMap could not safely save the restored entitlement. Free some device storage and retry.", listOf())
    fun liveLocationFirstLaunch(): String =
        L10n.message("id.ui_tacmap_requests_location_access_on_first_launch__581e58e5", "TacMap requests Location access on first launch. Tap to request it again if needed.")
    fun liveLocationFirstLaunchMessage(): LocalizedMessage =
        LocalizedMessage("id.ui_tacmap_requests_location_access_on_first_launch__581e58e5", "TacMap requests Location access on first launch. Tap to request it again if needed.", listOf())
    fun billingTacmapSavedYourPurchaseButGooglePlayHasNot(): String =
        L10n.message("id.ui_tacmap_saved_your_purchase_but_google_play_has_n_c7732e0b", "TacMap saved your purchase, but Google Play has not confirmed its acknowledgement. Your access remains available. Retry soon to avoid Play automatically refunding an unacknowledged purchase.")
    fun billingTacmapSavedYourPurchaseButGooglePlayHasNotMessage(): LocalizedMessage =
        LocalizedMessage("id.ui_tacmap_saved_your_purchase_but_google_play_has_n_c7732e0b", "TacMap saved your purchase, but Google Play has not confirmed its acknowledgement. Your access remains available. Retry soon to avoid Play automatically refunding an unacknowledged purchase.", listOf())
    fun billingTheGooglePlayPriceIsNotReadyYetRetry(): String =
        L10n.message("id.ui_the_google_play_price_is_not_ready_yet_retry_to__ae5677c5", "The Google Play price is not ready yet. Retry to load it.")
    fun billingTheGooglePlayPriceIsNotReadyYetRetryMessage(): LocalizedMessage =
        LocalizedMessage("id.ui_the_google_play_price_is_not_ready_yet_retry_to__ae5677c5", "The Google Play price is not ready yet. Retry to load it.", listOf())
    fun billingThePurchaseWindowCouldNotOpenReturnToTacmap(): String =
        L10n.message("id.ui_the_purchase_window_could_not_open_return_to_tac_790f34d5", "The purchase window could not open. Return to TacMap and try Unlock again.")
    fun billingThePurchaseWindowCouldNotOpenReturnToTacmapMessage(): LocalizedMessage =
        LocalizedMessage("id.ui_the_purchase_window_could_not_open_return_to_tac_790f34d5", "The purchase window could not open. Return to TacMap and try Unlock again.", listOf())
    fun billingTheTacmapUnlockProductIsNotAvailableForThis(): String =
        L10n.message("id.ui_the_tacmap_unlock_product_is_not_available_for_t_9d8a3562", "The TacMap unlock product is not available for this Play Store account.")
    fun billingTheTacmapUnlockProductIsNotAvailableForThisMessage(): LocalizedMessage =
        LocalizedMessage("id.ui_the_tacmap_unlock_product_is_not_available_for_t_9d8a3562", "The TacMap unlock product is not available for this Play Store account.", listOf())
    fun billingTheTacmapUnlockProductIsNotCurrentlyAvailableFrom(): String =
        L10n.message("id.ui_the_tacmap_unlock_product_is_not_currently_avail_ed188837", "The TacMap unlock product is not currently available from Google Play. Retry, or check that you are using the Play Store build.")
    fun billingTheTacmapUnlockProductIsNotCurrentlyAvailableFromMessage(): LocalizedMessage =
        LocalizedMessage("id.ui_the_tacmap_unlock_product_is_not_currently_avail_ed188837", "The TacMap unlock product is not currently available from Google Play. Retry, or check that you are using the Play Store build.", listOf())
    fun billingThisBuildCannotStartTheConfiguredGooglePlayPurchase(): String =
        L10n.message("id.ui_this_build_cannot_start_the_configured_google_pl_66554d76", "This build cannot start the configured Google Play purchase. Install the Play Store release and try again.")
    fun billingThisBuildCannotStartTheConfiguredGooglePlayPurchaseMessage(): LocalizedMessage =
        LocalizedMessage("id.ui_this_build_cannot_start_the_configured_google_pl_66554d76", "This build cannot start the configured Google Play purchase. Install the Play Store release and try again.", listOf())
    fun recordingBuildPrerequisite(): String =
        L10n.message("id.ui_this_build_is_missing_an_android_foreground_loca_d9bda81b", "This build is missing an Android foreground-location service prerequisite.")
    fun recordingBuildPrerequisiteMessage(): LocalizedMessage =
        LocalizedMessage("id.ui_this_build_is_missing_an_android_foreground_loca_d9bda81b", "This build is missing an Android foreground-location service prerequisite.", listOf())
    fun billingThisGooglePlayVersionDoesNotSupportInApp(): String =
        L10n.message("id.ui_this_google_play_version_does_not_support_in_app_ad901add", "This Google Play version does not support in-app purchases. Update the Play Store and retry.")
    fun billingThisGooglePlayVersionDoesNotSupportInAppMessage(): LocalizedMessage =
        LocalizedMessage("id.ui_this_google_play_version_does_not_support_in_app_ad901add", "This Google Play version does not support in-app purchases. Update the Play Store and retry.", listOf())
    fun recordingFixFailed(detail: String): String =
        L10n.message("id.ui_track_fix_not_saved_recording_stopped_1_7a513ad8", "Track fix not saved; recording stopped: %1\$s", detail)
    fun recordingFixFailedMessage(detail: String): LocalizedMessage =
        LocalizedMessage("id.ui_track_fix_not_saved_recording_stopped_1_7a513ad8", "Track fix not saved; recording stopped: %1\$s", listOf(detail))
    fun recordingVisibleRequired(): String =
        L10n.message("id.ui_track_recording_can_only_be_started_while_tacmap_3471f4ab", "Track recording can only be started while TacMap is visible.")
    fun recordingVisibleRequiredMessage(): LocalizedMessage =
        LocalizedMessage("id.ui_track_recording_can_only_be_started_while_tacmap_3471f4ab", "Track recording can only be started while TacMap is visible.", listOf())
    fun recordingPrerequisitesUnavailable(): String =
        L10n.message("id.ui_track_recording_prerequisites_are_unavailable_363d5a9f", "Track recording prerequisites are unavailable.")
    fun recordingPrerequisitesUnavailableMessage(): LocalizedMessage =
        LocalizedMessage("id.ui_track_recording_prerequisites_are_unavailable_363d5a9f", "Track recording prerequisites are unavailable.", listOf())
    fun billingUnlockStatusNeedsAttention(): String =
        L10n.message("id.ui_unlock_status_needs_attention_f49aa5e4", "Unlock status needs attention")
    fun billingUnlockStatusNeedsAttentionMessage(): LocalizedMessage =
        LocalizedMessage("id.ui_unlock_status_needs_attention_f49aa5e4", "Unlock status needs attention", listOf())
    fun recordingAwaitingPermission(): String =
        L10n.message("id.ui_waiting_for_precise_location_permission_9db6f154", "Waiting for Precise location permission…")
    fun recordingAwaitingPermissionMessage(): LocalizedMessage =
        LocalizedMessage("id.ui_waiting_for_precise_location_permission_9db6f154", "Waiting for Precise location permission…", listOf())
    fun recordingAwaitingNotification(): String =
        L10n.message("id.ui_waiting_for_the_recording_notification_choice_b6d01585", "Waiting for the recording notification choice…")
    fun recordingAwaitingNotificationMessage(): LocalizedMessage =
        LocalizedMessage("id.ui_waiting_for_the_recording_notification_choice_b6d01585", "Waiting for the recording notification choice…", listOf())
    fun waypointsAreEncryptedAndLocked(detail1: String): String =
        L10n.message("id.ui_waypoints_are_encrypted_and_locked_1_93dedbe5", "Waypoints are encrypted and locked. %1\$s", detail1)
    fun waypointsAreEncryptedAndLockedMessage(detail1: String): LocalizedMessage =
        LocalizedMessage("id.ui_waypoints_are_encrypted_and_locked_1_93dedbe5", "Waypoints are encrypted and locked. %1\$s", listOf(detail1))
    fun waypointsAreLockedAndTheChangeWasNotSaved(): String =
        L10n.message("id.ui_waypoints_are_locked_and_the_change_was_not_save_f2b9af87", "Waypoints are locked and the change was not saved.")
    fun waypointsAreLockedAndTheChangeWasNotSavedMessage(): LocalizedMessage =
        LocalizedMessage("id.ui_waypoints_are_locked_and_the_change_was_not_save_f2b9af87", "Waypoints are locked and the change was not saved.", listOf())
    fun billingYourGooglePlayPaymentIsPendingTacmapUnlocksAfter(): String =
        L10n.message("id.ui_your_google_play_payment_is_pending_tacmap_unloc_f7750693", "Your Google Play payment is pending. TacMap unlocks after Play confirms it.")
    fun billingYourGooglePlayPaymentIsPendingTacmapUnlocksAfterMessage(): LocalizedMessage =
        LocalizedMessage("id.ui_your_google_play_payment_is_pending_tacmap_unloc_f7750693", "Your Google Play payment is pending. TacMap unlocks after Play confirms it.", listOf())
    fun waypointsQuarantined(value: String): String =
        L10n.message("id.waypoints_quarantined", "Saved waypoints could not be read and were set aside (%1\$s). Starting with no waypoints.", value)
    fun waypointsQuarantinedMessage(value: String): LocalizedMessage =
        LocalizedMessage("id.waypoints_quarantined", "Saved waypoints could not be read and were set aside (%1\$s). Starting with no waypoints.", listOf(value))
    fun weatherFetchFailed(): String =
        L10n.message("id.weather_fetch_failed", "Couldn't fetch conditions. If online lookups are off (Settings, Privacy & OPSEC), enable them; otherwise check your connection.")
    fun weatherFetchFailedMessage(): LocalizedMessage =
        LocalizedMessage("id.weather_fetch_failed", "Couldn't fetch conditions. If online lookups are off (Settings, Privacy & OPSEC), enable them; otherwise check your connection.", listOf())
    fun dayCount(count: Int): String = L10n.quantity("day", count)
    fun pointCount(count: Int): String = L10n.quantity("point", count)
    fun drawingCount(count: Int): String = L10n.quantity("drawing", count)
    fun waypointCount(count: Int): String = L10n.quantity("waypoint", count)
    fun unitCount(count: Int): String = L10n.quantity("unit", count)
    fun taskCount(count: Int): String = L10n.quantity("task", count)
    fun markerCount(count: Int): String = L10n.quantity("marker", count)
    fun lineCount(count: Int): String = L10n.quantity("line", count)
    fun freeDrawCount(count: Int): String = L10n.quantity("free-draw", count)
    fun areaCount(count: Int): String = L10n.quantity("area", count)
    fun trackRecordedCount(count: Int): String = L10n.quantity("track_recorded", count)
    fun trialRemainingCount(count: Int): String = L10n.quantity("trial_remaining", count)
    fun unreadCount(count: Int): String = L10n.quantity("unread", count)
    fun sendUnitsCount(count: Int): String = L10n.quantity("send_units", count)
    fun minuteAgoCount(count: Int): String = L10n.quantity("minute_ago", count)
    fun hourAgoCount(count: Int): String = L10n.quantity("hour_ago", count)
    fun objectCount(count: Int): String = L10n.quantity("object", count)
    fun layerCount(count: Int): String = L10n.quantity("layer", count)
    fun newWaypointCount(count: Int): String = L10n.quantity("new_waypoint", count)
    fun newDrawingCount(count: Int): String = L10n.quantity("new_drawing", count)
    fun newLayerCount(count: Int): String = L10n.quantity("new_layer", count)
}
