// Generated by scripts/generate_localizations.py. Do not edit.
package com.tacmap.localization

enum class SupportedLanguage(val tag: String, private val nativeName: String) {
    SYSTEM("system", ""),
    ENGLISH("en", "English"),
    GERMAN("de", "Deutsch");
    val label: String get() = if (this == SYSTEM) Messages.deviceLanguage() else nativeName
}
